skim:
  input_tree: Events
  other_trees:
    - LuminosityBlocks
    - Runs
  sel_ref: selection
  column_filters:
    - drop Jet_btagDeepB
    - drop Jet_btagDeepCvB
    - drop Jet_btagDeepCvL
    - drop Jet_btagCSVV2
    - drop Jet_qgl
    - drop Jet_neHEF
    - drop Jet_chFPV0EF
    - drop Jet_hfsigmaEtaEta
    - drop Jet_hfsigmaPhiPhi
    - drop Jet_hfcentralEtaStripSize
    - drop Jet_hfadjacentEtaStripsSize
    - drop Jet_nElectrons
    - drop Jet_electronIdx1
    - drop Jet_electronIdx2
    - drop Electron_sieie
    - drop Electron_jetRelIso
    - drop Electron_r9
    - drop Electron_jetPtRelv2
    - drop Electron_hoe
    - drop Electron_dr03EcalRecHitSumEt
    - drop Electron_dr03HcalDepth1TowerSumEt
    - drop Electron_jetNDauCharged
    - drop Electron_dr03TkSumPt
    - drop Electron_dr03TkSumPtHEEP
    - drop Electron_tightCharge
    - drop Electron_lostHits
    - drop Electron_cutBased_HEEP
    - drop Muon_dxybs
    - drop Muon_segmentComp
    - drop Muon_jetRelIso
    - drop Muon_jetPtRelv2
    - drop Muon_nStations
    - drop Muon_jetNDauCharged
    - drop ^(n|)Tau(_.*|)$
    - drop ^(n|)boostedTau(_.*|)$
    # - drop ^(n|)SV(_.*|)$
    - drop ^(n|)OtherPV(_.*|)$
    - drop Photon_genPartIdx
    - drop Photon_haloTaggerMVAVal
    - drop Photon_hasConversionTracks
    - drop Photon_seedGain
    - drop Photon_seediEtaOriX
    - drop Photon_seediPhiOriY
    - drop Photon_x_calo
    - drop Photon_y_calo
    - drop Photon_z_calo
    - drop ^(n|)LowPtElectron(_.*|)$
    - drop ^(n|)SoftActivityJet(.*|)$
    - drop ^(n|)IsoTrack(_.*|)$
    - drop ^(n|)GenDressedLepton(_.*|)$
    - drop ^(n|)GenIsolatedPhoton(_.*|)$
    - drop ^(n|)GenProton(_.*|)$
    - drop ^(n|)Proton(_.*|)$
    - drop ^(n|)PPSLocalTrack(_.*|)$
    - drop ^L1_.*$
    - drop ^HLT_.*$
    # - keep ^HLT_.*Tau.*$
    # - keep ^HLT_PFMET.*$
    # - keep ^HLT_PFHT.*$
    - keep ^HLT_(|Iso|Old)(|Tk)Mu[1-9][0-9]+.*$
    - keep ^HLT_Ele[1-9][0-9]+.*$
    - drop ^HLT_Ele.*CaloId.*$
    # - keep ^HLT_Ele[1-9][0-9]+.*CaloId.*PFJet.*$
    # - keep ^HLT_Photon[0-9]+_TwoProngs[0-9]+$
    # - keep ^HLT_Quad(|PF)Jet.*$
    # - keep ^HLT_MonoCentralPFJet.*$
    # - keep ^HLT_AK8PFJet[0-9]+.*BoostedDoubleB.*$
    # - keep ^HLT_Diphoton.*NoPixelVeto.*$
    - keep ^HLT_Diphoton.*
    - keep ^HLT_Ele.*Ele.*$
    - drop ^HLT_.*Tau3[mM]u.*$
    # - drop ^HLT_Mu.*(Ele|Mu|Jpsi|Upsilon|NoFilters|IP).*
    - drop ^HLT_Mu.*(Jpsi|Upsilon|NoFilters|IP).*

skim_failed:
  input_tree: Events
  output_tree: EventsNotSelected
  sel_ref: selection
  invert_sel: true
  column_filters:
    - drop ^.*$
    - keep ^LHE_.*$
    - keep genWeight
    - keep ^Pileup_(nPU|nTrueInt)$

selection: "
  auto ele_base_sel = Electron_pt > 7 && (abs(Electron_eta) < 2.5 || abs(Electron_eta+Electron_deltaEtaSC)<2.5) && abs(Electron_dz) < 1.0 && abs(Electron_dxy) < 0.5;
  auto ele_mvaIso_sel = Electron_mvaIso_WPL || Electron_mvaIso_WP90;
  auto ele_mvaNoIso_sel = Electron_mvaNoIso_WP90;
  auto ele_pfIso_sel = Electron_pfRelIso03_all < 0.5;
  auto ele_sel = ele_base_sel && (ele_mvaIso_sel || (ele_mvaNoIso_sel && ele_pfIso_sel));

  auto muon_base_sel = Muon_pt > 5 && abs(Muon_eta) < 2.4 && abs(Muon_dz) < 1.0 && abs(Muon_dxy) < 0.5;
  auto muon_id_sel = Muon_tightId || Muon_mediumId || Muon_looseId || Muon_highPtId;
  auto muon_iso_sel = Muon_pfRelIso04_all < 0.5 || Muon_pfRelIso03_all < 0.5 || Muon_tkRelIso < 0.5;
  auto muon_sel = muon_base_sel && muon_id_sel && muon_iso_sel;

  auto photon_sel = Photon_pt > 10 && (Photon_isScEtaEB || Photon_isScEtaEE) && Photon_electronVeto;

  int n_electrons = Electron_pt[ele_sel].size();
  int n_muons = Muon_pt[muon_sel].size();
  int n_photons = Photon_pt[photon_sel].size();

  return (n_electrons + n_muons >= 2) && (n_photons >= 1);
  "
